version: '3.1'
services:
    nginx:
        image: nginx:latest
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./code:/var/www/html:rw
            - ./nginx/log:/var/log/nginx/
        depends_on:
            - php
    php:
        image: romson/php:7.2.5-fpm
        restart: always
        volumes:
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ./code:/var/www/html:rw
    mysql:
        image: mysql:latest
        restart: always
        ports:
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        env_file:
            - ./mysql/environment.env
